spring.application.name=bff-agendador-tarefas

usuario.url =localhost:1974/usuario
notificacao.url=localhost:1920/email

server.port = 1750

agendador-tarefas.url=localhost:1955/tarefas

cron.horario=0 0/5 * * * ?

usuario.email= daniel.yassuo.rodrigues@gmail.com
usuario.senha= Seropri@1
